### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [soulwing/crypt4j#3]
Hi
The following lines have cryptographic API misuses. <br> File name => src/main/java/org/soulwing/crypt4j/Type.java: Line number => 77: API name => MessageDigest:Unexpected call to method update on object of type java.security.MessageDigest. Expect a call to one of the following methods reset<BR>

**Comment by ceharris** [comment]
Looks like whatever tool you're using to look for misuses isn't working correctly (or perhaps I just don't understand the output). The line of code referenced is not invoking MessageDigest.update. It invokes MessageDigest.getInstance,
